subscriptions: Fix infinite hang for non-admin users
`subscription-manager list` and `status` fail with

    Error: this command requires root access to execute <unavailable>

for non-administrators. This causes the Subscriptions page to eternally
show the "Retrieving subscription status.." spinner.

Change the invocation to require superuser privileges (as other commands
on the page already do), to properly invoke the "current user isn't
allowed to access subscription status" curtain.

https://bugzilla.redhat.com/show_bug.cgi?id=1442540

Closes #8475