bridge: Fix optional OSError.errno mypy error in FsInfoChannel
mypy 1.14 now complains about an `arg-type` issue:

> src/cockpit/channels/filesystem.py:565: error:
> Argument 1 to "report_error" of "FsInfoChannel" has incompatible type "int | None"; expected "int"

In our case we know that `Handle.open` will always fail with a valid
errno, so assert it. This requires an additional noqa marker, as
otherwise ruff complains about using `assert` in an `except` handler.