test: Ignore `machine.image_file` type check failure
For the last few weeks/months, running static-code locally has always
failed like this for me:

```
test/common/testlib.py:1440: error: "Machine" has no attribute "image_file"  [attr-defined]
test/common/testlib.py:1441: error: "Machine" has no attribute "image_file"  [attr-defined]
```

This wasn't showing up in our official CI as that ran without bots/. Fix
the unit-tests workflow to include bots, so that testlib.py can be
checked against bots types.

Due to the dynamic class determination we cannot properly annotate this,
so just ignore the attribute check.