test: Bump up location change rate limiter in Firefox
There are 200 allowed changes in 10 seconds by default. Bump it up to
9999 otherwise tests can hit this and then fail with:
```
Too many calls to Location or History APIs within a short timeframe.
SecurityError: The operation is insecure.
```

Fixes #14720