tools: Make SELinux policy changes idempotent
Don't fail when updating from a previous version that already applied
the `fcontext` fixes. This command is not idempotent and fails with

    ValueError: File context for /usr/libexec/cockpit-tls already defined