bots: Ignore OSError when parsing tests data files
These files can produce CRC errors when truncated. Any missing
data will be pulled again from GitHub and test logs, which means
that it'll converge on a good state.

Here's an example of such an error:

    OSError: CRC check failed 0x8bc96dfc != 0x32aface1