lib: Type cockpit.dbus().proxies()
Fix the last remaining instance of

> error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

That was because the DBusProxies() function was not considered a class
constructor, as it did not assign to `this`. So do that for its
properties, and only use `defineProperties()` for declaring their
read-onliness. Thanks Marius Vollmer for figuring this out!