ws: Fix theoretical leak in test_multi_step_fail()
Formally it could happen that the parse_login_reply_challenge() call
happens during the last iteration and thus `id` never gets free'ed
(which happens in the next iteration).

This does not happen in practice in the test case, but coverity can't
really know that, and thus complains:

    Error: RESOURCE_LEAK (CWE-772): [#def2]
    src/ws/test-auth.c:953: alloc_arg: "parse_login_reply_challenge" allocates memory that is stored into "id".
    src/ws/test-auth.c:990: leaked_storage: Variable "id" going out of scope leaks the storage it points to.

Mark `id` as autofree to pacify it.