bots: Fix path that github code uses to lookup git repo
If we've checked out a different directory in the meantime
the tasks or bots subdirectory may no longer exist.

OSError: [Errno 2] No such file or directory: '/build/cockpit/bots/task/..'