bots: Work around mock --offline regression on latest Fedora mock configs
mock-core-configs 28 now sets `skip_if_unavailable=False` which breaks
`--offline` builds:

    Error: Cache-only enabled but no cache for 'fedora'

Drop that option again. See https://bugzilla.redhat.com/show_bug.cgi?id=1549291