test: Fix flake in check-realms
`testIpaUnqualifiedUsers` reboots, but forgot to allow the corresponding
messages. Fixes this failure:

```
Error: org.freedesktop.PackageKit: couldn't get all properties of org.freedesktop.PackageKit.Transaction at /5_beedcbdc: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```