packagekit: Ignore invalid bug URLs
On RHEL, PackageKit's `UpdateDetail` signal has `bugzilla_urls` entries
which are not URLs, but are bug titles for the previous or next list
entry (https://bugs.freedesktop.org/show_bug.cgi?id=104552). Filter
entries which are actually displayable http:// or https:// URLs to fix
that, and ignore the rest.

Add a `title` field to the yum updateinfo XML. This results in

```
Traceback (most recent call last):
  File "test/verify/check-packagekit", line 209, in testInfoSecurity
    self.assertEqual(b.text("#app .listing-ct tbody:nth-of-type(3) td:nth-of-type(2)"), "123, 456")
AssertionError: u'Bug#123 Description, Bug#456 Description, 123, 456' != '123, 456'
```

and thus reproduces the bug.

Fixes #8376
Closes #8378