websocket: Fix memory leak in parse_handshake_request()
Spotted by coverity:
```
Error: RESOUdRCE_LEAK (CWE-772): [#def24]
cockpit-237/src/websocket/websocketserver.c:263: alloc_arg: "web_socket_util_parse_req_line" allocates memory that is stored into "method".
cockpit-237/src/websocket/websocketserver.c:273: leaked_storage: Variable "method" going out of scope leaks the storage it points to.
cockpit-237/src/websocket/websocketserver.c:263: alloc_arg: "web_socket_util_parse_req_line" allocates memory that is stored into "resource".
cockpit-237/src/websocket/websocketserver.c:287: leaked_storage: Variable "resource" going out of scope leaks the storage it points to.
```

Move to automatic memory management to also free these two variables in
the error exit paths.

Part of https://bugzilla.redhat.com/show_bug.cgi?id=1938693