jsonutil: reorganize our Json* type names
We pass around an awful lot of JsonObject and JsonDocument throughout
the bridge, which can be a problem sometimes, because you often get
messages like:

  error: Argument "headers" has incompatible type "dict[str, str]"; expected "JsonDocument"  [arg-type]
  note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
  note: Consider using "Mapping" instead, which is covariant in the value type

when trying to pass something which seems like it should be a perfectly
valid JsonObject.

The issue here is that the object time we're passing has a more specific
type (in this case, it only accepts string values), and we don't know
that the function we're passing it to doesn't intend to write to it.
Mapping solves this by being read-only, which allows for covariance, as
noted in the message above.

At the same time: there are a few cases where we do intend to create
values and modify them.

Additionally: I've regretted the name JsonDocument almost since I chose
it.  I think this would be better called JsonValue.

As a solution to this problem: we introduce two parallel sets of Json
types:

 - JsonObject and (newly introduced) JsonValue are immutable — they are
   defined using Mapping and Seqeunce and are fully covariant.  Any
   mapping (or dictionary) type that contains JSON data can be passed as
   an argument for a function expecting a JsonObject.

 - JsonDocument continues to refer to a mutable JSON document, with the
   newly-introduced JsonDict type referring to a JsonObject which is
   definitely implemented as a dictionary, and therefore supports
   writing (but at the cost of being invariant when used as an argument
   type).  JsonDict and JsonDocument also expect lists to be used.

The idea is that most places will use JsonObject and JsonValue, and
JsonDocument and JsonDict will be reserved for places where they're
truly required (ie: functions which modify their arguments or return
values that are intended to be modified).