python: Ignore packages with broken or empty manifest.json
This is covered by at least `TestCurrentMetrics.testDiskIO`, which makes
the bridge crash with

    JSONDecodeError: Expecting value: line 1 column 1 (char 0)