test: Remove extra valkey packages on RHEL
Since a new RHEL 10.3 refresh the test failed with:

error: Failed dependencies:
	valkey(x86-64) = 8.1.6-1.el10 is needed by (installed) valkey-rdma-8.1.6-1.el10.x86_64
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-metrics", line 1370, in testBasic
    m.execute(f"rpm --erase --verbose pcp python3-pcp {redis_package} {' '.join(extra_packages)}")