ws: Fix EAGAIN/EINTR handling in test-kerberos
The error handler was missing braces, spotted by coverity:
```
Error: COMPILER_WARNING (CWE-483): [#def45]
cockpit-240.12.g36d8c0668/src/ws/test-kerberos.c: scope_hint: In function 'mock_kdc_start'
cockpit-240.12.g36d8c0668/src/ws/test-kerberos.c:406:11: warning[-Wmisleading-indentation]: this 'if' clause does not guard...
cockpit-240.12.g36d8c0668/src/ws/test-kerberos.c:408:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
```

Fix the code to retry the read on EAGAIN/EINTR instead of breaking the
loop. Eliminate the `else` branch to improve readability and avoid the
unnecessary nesting.

Note: We can't yet enable this warning as `-Werror` in configure.ac as
gcc in our unit-tests container does not yet know about it.