packagekit: Re-drop triggerRef from PackageList
Commit 17c4be5515f9 introduced this to avoid the Tooltip's `<div>`
nesting in between the `<ul>` and the `<li>`. But this causes page
oopses in some situations:

> error: Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

(which of course is a perfectly clear and obvious error message.. not).

Re-simplify this again, and just restructure the DOM to put the Tooltip
inside of the list item.

As a nice side effect, this also centers the tooltip arrow on the
package name, instead of looking weirdly off (as they were centered on
the table cell).

Fixes #22297