test: Fix cases where we race with tmp/run directory creation
We're seeing this error in some tests. This is due to multiple
TEST_JOB's trying to create the directory at once.

OSError: [Errno 17] File exists: '/build/cockpit/test/common/../tmp/run'