bridge: Fix time_t format string in test_metrics_archive_timestamp_now()
On 32 bit architectures, `time_t` can now be a 64 bit type, so that
printing a `long` (32 bit) is not sufficient. Print/cast the time_t into
a `long long` to ensure that it works on all architectures.

Fixes build failure on x32:

    src/bridge/test-pcp-archives.c: In function ‘test_metrics_archive_timestamp_now’:
    src/bridge/test-pcp-archives.c:321:44: error: format ‘%li’ expects argument of type ‘long int’,
        but argument 2 has type ‘time_t’ {aka ‘long long int’} [-Werror=format=]