test: Ignore SELinux violation for firewalld/nft on rhel-8
This causes loads of tests to fail due to

    Error: audit: type=1400 audit(1525261178.267:302): avc:  denied  { create } for  pid=1565 comm="nft" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=netlink_netfilter_socket permissive=0

See <https://bugzilla.redhat.com/show_bug.cgi?id=1573501>.