test: Fix running check-realms standalone
`parent` needs to be imported first, before `packagelib`. Otherwise it
fails with

```
test/verify/check-realms TestRealms.testIpa
Traceback (most recent call last):
  File "test/verify/check-realms", line 24, in <module>
    import packagelib
  File "/home/martin/upstream/c2/test/verify/packagelib.py", line 23, in <module>
    from testlib import *
ModuleNotFoundError: No module named 'testlib'
```

Regression introduced in commit  3f04aeb5.