webpack: don't generate jquery.js and cockpit.js
For local development you can run `webpack` with `--watch` parameter
to have automatic syncing of changes done to source files.

However, this will also override `dist/base1/jquery.js` file with clean
upstream jquery.js that lacks tooltip from bootstrap and some other
merged plugins.  If you want to run `./test/verify/check-***` it will
fail with "RuntimeError: TypeError: r.tooltip is not a function".

Since commit <161266d99e4450ec8856adf5b3716397d3e32b19> the direct
invocation of `webpack` was removed from `HACKING.md` and you should
always run `make` we can safely remove the generation.

This was reintroduced by commit <2b2e9ab2eb2ff3746efbba16129bb8af3de467ab>.

Signed-off-by: Pavel Hrdina <phrdina@redhat.com>