bots: Use libvirt XML instead of raw qemu args for bridge
In Fedora 29, `<qemu:arg>` does not work any more for defining a bridge,
as this breaks limitations of `-sandbox on`:

    $ test/vm-run --network cirros
    libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: 2018-10-31 07:15:57.311+0000: Domain id=8 is tainted: custom-argv
    2018-10-31T07:15:57.486306Z qemu-system-x86_64: bridge helper failed

qemu cannot run external programs like the bridge helper with
sandboxing.

Move the cockpit1 bridge definition to libvirt XML, in which case
libvirt starts the bridge helper by itself. Unfortunately the same does
not work for mcast; this ought to be

    <interface type="mcast">
      <source address="230.0.0.1" port="{mcast}"/>
      <mac address="{mac}"/>
      <model type="rtl8139"/>
    </interface>

but with that, there is no DHCP server for the VM and thus it does not
have any outside networking.

https://bugzilla.redhat.com/show_bug.cgi?id=1643853