bots: Fix ostree remote URL on Atomic
There was an extra `/` in the "local" remote URL which is now illegal in
Fedora 28:
```
file:////var/local-repo
error: [3] URL using bad/illegal format or missing URL
```