test: Fix unexpected message in check-pages
test{Shell,Frame}Reload sometimes fail with

    testlib.Error: Error receiving data: Connection reset by peer

due to the page reload. Allow restart messages in general.

Drop the specific "Connection reset" filter from testPtBRLocale, as that
already calls the more general allow_restart_journal_messages().

Closes #10250