build: Don't install pcp manifest with --disable-pcp
Installing the manifest will confuse the UI.

It also fails the rpm build due to
```
error: Installed (but unpackaged) file(s) found:
   /usr/share/cockpit/pcp/manifest.json
```