test: bump ruff target-version for tests
Without setting a target version ruff complains about our usage of
modern Python f-strings:

```
SyntaxError: Cannot reuse outer quote character in f-strings on Python 3.9
```

While our tests run in the tasks container which has a modern Python in
contrast to cockpit-bridge which supports older Python versions.

Cherry-picked from main commit d63a333e68f7da4f8b