python: don't process kill messages on closing channels
We guard for the channel being in the closing state on incoming data and
control messages for the channel, but we forgot to add this same check
for .do_kill(), even thought the docs for .close() are pretty clear that
no .do_*() methods should get called after .close().

Add the same check as in the other places.

This fixes a backtrace recently seen in an unrelated PR:

  ...
    File "/usr/local/lib/python3.11/site-packages/cockpit/channel.py", line 150, in do_kill
      self.do_close()
    File "/usr/local/lib/python3.11/site-packages/cockpit/channels/dbus.py", line 505, in do_close
      for slot in self.matches:
  TypeError: 'NoneType' object is not iterable