test: Ignore AppStream XML parser errors in TestSOS.testAppStream
If chromium is installed in the testbed (which is the case in gating
tests), this test fails on two unexpected messages:

    /usr/share/metainfo/chromium-browser.appdata.xml:   File "<string>", line None
    xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 2, column 0

Ignore all xml related messages in this test.