lib: Type cockpit.dbus().proxies()
This leaves one annoying instance of

> error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.

That's because the DBusProxies() function isn't a real class, and
it's not external API so we can't easily annotate it. Type the publicly
visible result of `dbus().proxies()` and ignore that one remaining
internal instance. We want to avoid introducing more of these.