pcp: Fix cast
I cannot build the source due to this error:
```
src/bridge/cockpitpcpmetrics.c: In function ‘convert_metric_description’:
src/bridge/cockpitpcpmetrics.c:516:25: error: passing argument 2 of ‘pmLookupName’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  516 |   rc = pmLookupName (1, (char **)&info->name, &info->id);
      |                         ^~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         char **
In file included from src/bridge/cockpitpcpmetrics.c:29:
/usr/include/pcp/pmapi.h:266:39: note: expected ‘const char **’ but argument is of type ‘char **’
  266 | PCP_CALL extern int pmLookupName(int, const char **, pmID *);
      |                                       ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

This is broken API, thus we would need to conditionally differentiate
where we would use `const char **` and when just `char **`.