debian: Fix esbuild/nodejs build dependencies
esbuild on Debian's ppc64 keeps failing:

> TypeError: esbuild.context is not a function
>    at build (file:///build/reproducible-path/cockpit-354/build.js:207:43)

But making these build dependencies architecture specific was bogus
anyway: These are only relevant for the "Architecture: all" packages,
which are built on amd64. The bundle builds are just thrown away on all
other architectures.

So make this explicit and correct, and declare these as
`Build-Depends-Indep:` instead.