networkmanager: Fix null settings connection access
There are races in the code (which fail during testing) due to:

TypeError: null is not an object (evaluating 'i.Settings.connection')

In addition there are tons of places where we have to do this
repetitive check and get it wrong. Replace with an accessor function.