connect: Remove unused variable
Clang catches the issue:

  ../../src/connect.c:532:26: error: unused variable 'domain' [-Werror,-Wunused-variable]
      g_autoptr(virDomain) domain = NULL;
                           ^

Signed-off-by: Andrea Bolognani <abologna@redhat.com>
Reviewed-by: Ján Tomko <jtomko@redhat.com>