common: Avoid RESOURCE_LEAK coverity warning in test_memfd_error_cases()
All of the cockpit_memfd_read() calls are expected to fail in this test.
Add a missing `content == NULL` assertion to pacify Coverity:

```
Error: RESOURCE_LEAK (CWE-772): [#def13]
cockpit-237/src/common/test-jsonfds.c:423: alloc_fn: Storage is returned from allocation function "cockpit_memfd_read".
cockpit-237/src/common/test-jsonfds.c:423: var_assign: Assigning: "content" = storage returned from "cockpit_memfd_read(fd, &error)".
cockpit-237/src/common/test-jsonfds.c:432: overwrite_var: Overwriting "content" in "content = cockpit_memfd_read(fd, &error)" leaks the storage that "content" points to.
```

Part of https://bugzilla.redhat.com/show_bug.cgi?id=1938693