package.json: Update to latest PatternFly react-console
This fixes the pesky crash at last.

This pulls in @novnc/novnc, which uses ES6 syntax in its *.js files.
This leads to runtime errors like

    SyntaxError: export declarations may only appear at top level of a module

as these are embedded in webpacks. Until we update to a less ancient
weback, fix these by applying babel on the novnc sources.

Cherry-picked from master commit ccb6c5ce856f388