test: Fix verbose dumping of execute output
We have a problem when running check-connection with the -t
argument, due to dumping of non-ascii characters to output

    File "test/verify/check-connection", line 158, in testConfigOrigins
      output = m.execute('curl -s -f -N -H "Connection: Upg...
    File "/data/src/cockpit/test/common/testvm.py", line 464, in execute
      sys.stdout.write(data)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd'