ssh: Drop unused variable in on_channel_data()
This has existed since the initial commit b3a463baa2fa. Newer gcc
versions now spot this:

    src/ssh/cockpitsshrelay.c:1688:11: error: variable 'size' set but not used [-Werror,-Wunused-but-set-variable]
      guint32 size, i;
              ^
    1 error generated.

 Also make the `i` and `bytes` variables more local while we are at it.