python: Defer asyncio.Lock() creation for D-Bus
Initializing a global lock at program start is too early: At that point,
systemd_ctypes has not yet initialized its own main loop. In Python 3.6
this causes tons of crashes like

    RuntimeError: Task <Task pending coro=<DBusChannel.do_open.<locals>.get_ready() running at
    /usr/lib64/python3.6/site-packages/cockpit/channels/dbus.py:251>
    cb=[set.discard()]> got Future <Future pending> attached to a different loop

This also moves the lock from a class to an instance variable -- it's
not necessary to globally order messages, doing it for a single channel
is sufficient.