bots: Move openshift image to CentOS-7
Fedora 28 is EOL. As we still need Python 2 here, use CentOS 7 as a base
image (which will be around for a while).

Drop obsolete GnuTLS/Go certificate hack, current 3.11 OpenShift
versions have this fixed properly.

Move to virt-install-fedora to get rid of the libguestfs dependency and
be able to build this image in an unprivileged podman container.

Avoid putting the GitHub release page JSON blob into the log, as it
often causes image builds to fail due to

    BlockingIOError: [Errno 11] Resource temporarily unavailable

Closes #12693