naughty: Close 6332: Fedora: setroubleshootd API is broken:  AttributeError: module 'seobject' has no attribute 'boolean_desc'
Known issue which has not occurred in 23 days

Fedora: setroubleshootd API is broken:  AttributeError: module 'seobject' has no attribute 'boolean_desc'

Fixes #6332