test: fix removing packages on Arch Linux
The tests first remove fake-libnfs which fake-nfs-utils requires so we
need a bigger hammer to tell pacman to really remove the package.

[root@archlinux tmp]# pacman -R --noconfirm fake-libnfs
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing fake-libnfs breaks dependency 'fake-libnfs' required by
fake-nfs-utils