machines: Use cockpit.all() instead of Promise.all()
Otherwise the Machines page crashes with

    TypeError: Method Promise.prototype.then called on incompatible receiver #<Object>

when running against cockpit-system 185 (in RHEL 8.0). As we don't
enforce this through versioned dependencies, and don't want to, go back
to `cockpit.all()` for `ListNodeDevices()` and `DeleteVm()`, as some
other parts of the code already do.

Closes #11704