test: Fix run-tests changed_pkgs crash for non-cockpit projects
Commit 2db63f19efd4f57 regressed run-tests for non-cockpit projects:
```
fatal: ambiguous argument 'pkg/': unknown revision or path not in the working tree.
[...]
  File "starter-kit/test/common/run-tests", line 240, in <listcomp>
    changed_tests.extend([test for test in test_files if any(pkg in test for pkg in changed_pkgs)])
NameError: free variable 'changed_pkgs' referenced before assignment in enclosing scope
```

Fix this by explicitly telling git that `pkg/` is a path, by prefixing
it with `--`. Also, move the `changed_tests` extension into the right
scope, in case the git command still fails.