test: Retry BiDi pointer events on "no such element"
It can happen that the clicked element re-renders in between the
`wait_visible()` and the `input.performActions`. This caused random test
failures like

> testlib.Error: no such element: Origin element f.[...] was not found

Prevent this by retrying the `ph_find` + `performActions` up to 3 times
when that error happens.

Also update the obsolete "top frame with Chromium" comment, this was
fixed in commit 1b6a12676fd4.