tools: Ship polkit file on all OSes
Fix commit c2f2dd192, which accidentally put the file installation into
a conditionalized spec section. This caused RPM builds on RHEL/CentOS 7
to fail with

    error: Installed (but unpackaged) file(s) found:
        /usr/share/polkit-1/actions/org.cockpit-project.cockpit-bridge.policy