tests: Run commands under C locale by default
ssh takes the local environment's locale into the remote location, thus
when running tests in a non-English locale on an image which has the
corresponding translations, some tests fail like
```
  + curl -sS http://localhost:8080/api 2>&1 || true
  curl: (7) Failed connect to localhost:8080; Verbindungsaufbau abgelehnt
  not ok 1 testConnect (__main__.TestConnection) duration: 36s
  Traceback (most recent call last):
    File "test/verify/check-kubernetes", line 73, in testConnect
      self.assertIn("Connection refused", output)
  AssertionError: 'Connection refused' not found in 'curl: (7) Failed connect
                   to localhost:8080; Verbindungsaufbau abgelehnt\n'
```

Change Machine.execute() to always run the specified command or script
under the C locale. For testing actual translations this can then still
be overridden through the "environment" parameter.

In exchange, drop all "LC_ALL=C" from execute() calls as these are now
redundant.

Closes #6056