Revert "test: Improve image pruning logic"
It breaks tests: `ImportError: cannot import name testinfra`

This reverts commit 3d4890e38c05c1ae6b3740e2d041cf29d2a0540b.