systemd: Fix graphs having wrong `display` attribute
Similarly to PR #13265, use the `hidden` attribute for the graphs
instead of .show()/.hide(). The latter sets `display: none`, which
causes the widget to have a zero height, which causes flot to crash with

    Error: Invalid dimensions for plot, width = 647, height = 0 36 graphs.js:230:10
    resize http://localhost:9090/cockpit/@localhost/system/graphs.js:230

Fixes #13290
https://bugzilla.redhat.com/show_bug.cgi?id=1792623