systemd: guard against currentIdentifiers being undefined
The initial state of `currentIdentifiers` is undefined, while unlikely
to be triggered as prependEntries() is called after some promises are
done.

Adding a link to the logs page from cockpit-podman triggered and
clicking it in our tests triggered:

```
TypeError: Cannot read properties of undefined (reading 'includes')"]
```