bots: Show OpenShift release JSON on image creation failure
Refreshing the OpenShift image on the infrastructure often fails with
`AttributeError: 'str' object has no attribute 'get'` on parsing
<https://api.github.com/repos/openshift/origin/releases>. This isn't
reproducible locally and thus indicates some networking error in our
bots.

On failure, show the raw result of what it downloaded, to ease
debugging.

Closes #7340