test: Fix formatting of timeout messages
Commit 89cde583c inadvertently changed the formatting of timeout
messages from

  Error: timeout
  blabla

to

  Error: timeoutblabla

as the previous messages string always got a `\n` prepended. Add  it
back. This will still cause an extra newline if there is no message, but
this is fairly harmless.

This unbreaks all our naughty patterns that involve timeouts.