test: Mark asyncio.AbstractEventLoopPolicy deprecation
This is deprecated in 3.14 and will be removed in 3.16:

> test/pytest/conftest.py:47: error: Name "asyncio.AbstractEventLoopPolicy" is not defined  [name-defined]

For now, ignore the mypy error.