util: don't inline virtDBusUtilVirDomainListFreep
When building GCC reports that it'll never inline this method, so don't
mark it status+inline as that will cause multiple instances of it to be
defined in each source file that includes util.h

In file included from manager.c:4:0:
manager.c: In function ‘virtDBusManagerEnumarateDomains’:
util.h:62:1: error: inlining failed in call to ‘virtDBusUtilVirDomainListFreep.isra.0’: call is unlikely and code size would grow [-Werror=inline]
 virtDBusUtilVirDomainListFreep(virDomainPtr **domainsp)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
manager.c:17:61: note: called from here
     _cleanup_(virtDBusUtilVirDomainListFreep) virDomainPtr *domains = NULL;
                                                             ^~~~~~~

Reviewed-by: Pavel Hrdina <phrdina@redhat.com>
Signed-off-by: Daniel P. Berrange <berrange@redhat.com>