test: Wait for browser longer
This can happen on loaded infrastructures. 30 seconds just isn't
enough time for the browser to come up reliably. Bump by factor
of ten.

This was seen in Semaphore CI:

    Traceback (most recent call last):
      File "./test/common/tap-cdp", line 70, in <module>
        cdp.invoke("Page.navigate", url=address + '/' + opts.test)
      File "/tmp/source/test/common/cdp.py", line 87, in invoke
        res = self.command(cmd)
      File "/tmp/source/test/common/cdp.py", line 97, in command
        self.start()
      File "/tmp/source/test/common/cdp.py", line 199, in start
        raise RuntimeError('timed out waiting for browser to start')
    RuntimeError: timed out waiting for browser to start