common: Fix unused assignment in test_memfd_json_error_cases()
Fixes build failure with current clang:

    src/common/test-jsonfds.c:530:25: error: variable 'object' set but not used [-Werror,-Wunused-but-set-variable]
      g_autoptr(JsonObject) object = NULL;
                            ^