test: Fix unexpected message in TestRealms.testNotSupported
Joining a domain seems to restart realmd, and sometimes the subscription
check on the /system page hits the right moment and can't talk to its
D-Bus interface. This causes the test to fail with

    Error: com.redhat.SubscriptionManager: couldn't introspect /org/freedesktop/realmd:
    GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying