bridge: Initialize Channel._transport
When the channel fails early, i.e. when the websocket goes away and
writing the "ready" control message fails, then `Channel.do_close()` was
called before `.connection_made()`. This caused a bridge crash:

> AttributeError: 'SubprocessStreamChannel' object has no attribute '_transport'