tls: Add coverity annotation to false-positive leaked handle
This is a unit test, so we *always* expect `do_connect()` to fail in
teardown(). If it wouldn't, then the fd would indeed leak, but this
isn't relevant in practice:

    Error: RESOURCE_LEAK (CWE-772): [#def1]
    src/tls/test-server.c:378: open_fn: Returning handle opened by "do_connect".
    src/tls/test-server.c:378: var_assign: Assigning: "__n1" = handle returned from "do_connect(tc)".
    src/tls/test-server.c:378: leaked_handle: Handle variable "__n1" going out of scope leaks the handle.

 Add an annotation to quiesce this warning.

https://bugzilla.redhat.com/show_bug.cgi?id=1938693