test: Fix --sit with avocado/selenium tests
Avoid input(), as that doesn't work well with bilingual code.
Similar to what was done to the verify tests in commit 44e0fd48caa5c8.

Fixes this error:
```
  File "test/avocado/run-tests", line 262, in run_avocado
    input("Press RET to continue... ")
UnboundLocalError: local variable 'input' referenced before assignment
```

Closes #11281