test: Ignore unrelated messages about missing tuned
ubuntu-1604 and debian-stable don't have tuned. This occasionally causes
tests to fail with an unexpected message:

    Error: com.redhat.tuned: couldn't get managed objects at /org/freedesktop/realmd:
    GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown:
    The name com.redhat.tuned was not provided by any .service files

Ignore these messages on these two OSes.