doc: Drop wrong cockpit.user.onchanged()
`cockpit.user` is a simple function that will return a Promise. It's not
an event object, and trying to add an event listener to it fails:

    Uncaught TypeError: cockpit.user.addEventListener is not a function

There's also no reason to do this: The user of the current session
*never* changes. The only thing to wait for is for the value to become
available, which is what the promise does.

Thanks to Ivan Devat for finding and reporting this.