test: Add back missing "parent" import to check-packagekit
Commit c89fd22e5 dropped the "import parent" as it was causing a
"redefinition of unused parent" pyflakes error. But it is necessary to
be able to directly call test/verify/check-packagekit (otherwise it
fails with "ImportError: No module named testlib"). So put it back, and
instead rename the "parent" argument of assertHistory().