test: Fix verbose dumping of execute output harder
Commit 1105141a improved this, but not enough yet:
`test/verify/check-system-info TestSystemInfo.testBasic -tv` still fails
with

```
+ journalctl 2>&1 -o cat -p 5 SYSLOG_IDENTIFIER=cockpit-ws SYSLOG_IDENTIFIER=cockpit-bridge || true
Traceback (most recent call last):
  File "/build/cockpit/bots/../test/verify/check-system-info", line 188, in testBasic
    self.check_journal_messages()
  File "/build/cockpit/test/common/testlib.py", line 780, in check_journal_messages
    messages = machine.journal_messages(syslog_ids, 5)
  File "/build/cockpit/bots/machine/testvm.py", line 625, in journal_messages
    messages = self.execute(cmd).splitlines()
  File "/build/cockpit/bots/machine/testvm.py", line 465, in execute
    sys.stdout.write(data.decode('utf-8', 'ignore'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 58: ordinal not in range(128)
```

The previous approach of writing an unicode string to sys.stdout still
fails if `sys.stdout.encoding` is not set, and it seems wrong to change
it inside testvm.py. So move to completely ignoring the encoding layers
and just write the raw bytes to stdout/stderr.